from math import ceil

SPRITE_WIDTH = 24
FPS = 30
WOBBLE_COUNT = 3
TEXT_WOBBLE_TIME = .5
SLIDE_TIME = .1
SLIDE_FRAMES = FPS * SLIDE_TIME
TEXT_SQUISH = .85
WIN_TEXT = "congratulations"
WIN_TEXT_LEN = len(WIN_TEXT)
WIN_LETTER_APPEARS = int(ceil(WIN_TEXT_LEN / 2))
FRAMES_PER_WIN_LETTER = int(FPS / 10)
WIN_LETTER_FRAMES = int(FRAMES_PER_WIN_LETTER * WIN_LETTER_APPEARS)
SCREEN_WASH_FRAMES = int(FPS * .8)
WIN_END_WAIT = FPS
LEVEL_NAME_WAIT = FPS
SMALL_WAIT = FPS / 3
